.TH "ORGANICE" "17" "December 2020" "User Command"
.SH NAME
organice
.SH SYNOPSIS
.B organice
[
.B FLAG
]
[
.B "NEW DIRECTORIES"
]
.SH DESCRIPTION
Organice as in nice is a command line utility to make your life easier and organize everything in a breeze with the help of flags.
.PP
.B -n
Classify by name in a new directory.
.PP
.B -e
Classify by extension in a new directory.
.PP
.B "-h or --help"
Displays the options.
.SH AUTHOR
Santiago Pedroza Díaz
.SH BUGS
Do a notice on the github page.
.UR
<"https://github.com/snat-s/organice">
.UE
.SH COPYRIGHT
Copyright  ©  2020.   License  GPLv3+:  GNU  GPL  version   3   or   later
.UR
<"https://gnu.org/licenses/gpl.html">.
.UE
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.
