#+TITLE: Organice
#+DESCRIPTION: Organize your files from the terminal fast.
#+AUTHOR: Santiago Pedroza Diaz
** SYNOPSIS
=organice= [FLAG] [EXTENSION/PART OF THE NAME]...

** DESCRIPTION
Move files (by extension or part of their name) to a new directory.

|------------------+------------------------------------------------------------|
|------------------+------------------------------------------------------------|
| =-n=             | To move files by title to a new directory with name.       |
| =-e=             | To move files by extension.                                |
| =-r=             | At the moment only works with =-e=, it makes it recursive. |
| =-v=             | Display the version (it's alpha right now).                |
| =-h= or =--help= | Displays this information.                                 |

You can find the =organice= tool in the AUR as =organice-git=.
If you have yay you can do a simple =yay -S organice-git=

*** Exit status (it doesn't work right now):
- 0 if OK,
- 1 some files could not be copied.


** EXAMPLES
- $ organice -n Homework /(all of the files with "Homework" in their names will be stored in a new directory)/
- $ organice -e .pdf /(all of the pdf's of this directory are going to be stored in a new directory)/
- $ organice -er /(all of the files are going to be stored by extension in a new directory inside your current working directory)/

** AUTHOR
Santiago Pedroza Díaz

** REPORTING BUGS
Let me know of any bugs you can submit an issue or bug in github.

** COPYRIGHT
Copyright  ©  2020  Santiago Pedroza.   License  GPLv3+:  GNU  GPL  version   3   or   later
<https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.
