#+TITLE: Organice
#+DESCRIPTION: Organize your files from the terminal fast.
#+AUTHOR: Santiago Pedroza Diaz
* SYNOPSIS
organice [FLAG]/[EXTENSION]

* DESCRIPTION
Makes a directory and stores all the files in two main ways, by extension or by how many they are.
** -n To move files by title to a new directory with the name.
** -e To Move files by extension.
** -r at the moment it's just an idea, but it would make the flags -n and -e recursive.
** -v Display the version (Right now it's just alpha software so it doesn't have this).
** -h or --help to display this information (The help is fake :)).
** Exit status:
0 if OK,
1 some files could not be copied
* AUTHOR
Santiago Pedroza Díaz

* REPORTING BUGS
Let me know any bugs you can contact issue a bug in the github issues.

* COPYRIGHT
Copyright  ©  2020  Free  Software  Foundation,  Inc.   License  GPLv3+:  GNU  GPL  version   3   or   later
<https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.
